on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Build
        run: $lnContent = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $lnContent) {dotnet build $file.FullName}
      - name: Prepare environment
        run: $lnContent = Get-ChildItem -Recurse -Filter '*TreiberStack.dll'; foreach ($file in $lnContent) {coyote rewrite $file.FullName}
      - name: Test
        run: $lnContent = Get-ChildItem -Recurse -Filter '*.sln'; foreach ($file in $lnContent) {dotnet test $file.FullName}